require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rechargeamMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'react-native-ussd', :path => '../node_modules/react-native-ussd'

  target 'rechargeamMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rechargeamMobile-tvOS' do
  # Pods for rechargeamMobile-tvOS

  target 'rechargeamMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
